version: '3.8'
services:
  web:
    build: .
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:root@postgres/demodb
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: demodb
    ports:
    - "5432:5432"