version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: velo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      # - ./init_db/init.sql:/docker-entrypoint-initdb.d
  node:
    build: .
    command: npm run start
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://root:root@postgres/velo

volumes:
  local_pgdata:
  pgadmin-data: