version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: velo
    volumes:
      - ./pgdata:/var/lib/postgres/data

  node:
    build: .
    command: npm run start
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:root@postgres/velo